$pdf_mode = 5;

$xelatex = "xelatex -file-line-error -halt-on-error -interaction=nonstopmode -synctex=1 %O %S";
$xdvipdfmx = "xdvipdfmx -E -o %D %O %S";

@default_excluded_files = ("lshort-zh-cn-layout.tex");

$go_mode = 1;

$clean_ext = "los synctex.gz xdv";

$makeindex = "makeindex -s lshort-zh-cn.ist %O -o %D %S";
